In [ ]:
#Importing Libraries
import pandas as pd
import numpy as np

# Loading Data/Inspection

In [ ]:
#Loading data
#Spreadsheets uploaded to Jupyter notebook directory first
labels_df = pd.read_excel('FILE A.xlsx')
values_df = pd.read_excel('FILE B.xlsx')

In [ ]:
#Inspection of first 5 rows
labels_df.head()

,ExternalReference,Q2,Q3,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,...,Q10_1,Q10_2,Q10_3,Q10_4,Q10_5,Q10_6,Q10_7,Q10_8,Q10_9,Q10_8_TEXT
0,External Data Reference,"How, if at all, has employee pressure to engag...","How, if at all, has your company‚Äôs response ...","How, if at all, is your company communicating ...","How, if at all, is your company communicating ...","How, if at all, is your company communicating ...","How, if at all, is your company communicating ...","How, if at all, is your company communicating ...","How, if at all, is your company communicating ...","How, if at all, is your company communicating ...",...,"Which of the following, if any, does your comp...","Which of the following, if any, does your comp...","Which of the following, if any, does your comp...","Which of the following, if any, does your comp...","Which of the following, if any, does your comp...","Which of the following, if any, does your comp...","Which of the following, if any, does your comp...","Which of the following, if any, does your comp...","Which of the following, if any, does your comp...","Which of the following, if any, does your comp..."
1,"{""ImportId"":""externalDataReference""}","{""ImportId"":""QID129""}","{""ImportId"":""QID130""}","{""ImportId"":""QID131"",""choiceId"":""1""}","{""ImportId"":""QID131"",""choiceId"":""2""}","{""ImportId"":""QID131"",""choiceId"":""3""}","{""ImportId"":""QID131"",""choiceId"":""4""}","{""ImportId"":""QID131"",""choiceId"":""5""}","{""ImportId"":""QID131"",""choiceId"":""6""}","{""ImportId"":""QID131"",""choiceId"":""7""}",...,"{""ImportId"":""QID138"",""choiceId"":""1""}","{""ImportId"":""QID138"",""choiceId"":""2""}","{""ImportId"":""QID138"",""choiceId"":""3""}","{""ImportId"":""QID138"",""choiceId"":""4""}","{""ImportId"":""QID138"",""choiceId"":""5""}","{""ImportId"":""QID138"",""choiceId"":""6""}","{""ImportId"":""QID138"",""choiceId"":""7""}","{""ImportId"":""QID138"",""choiceId"":""8""}","{""ImportId"":""QID138"",""choiceId"":""9""}","{""ImportId"":""QID138_8_TEXT""}"
2,Response 1,Decreased,Stayed the same,Public statements or press releases,Company blog posts or thought leadership articles,Social media posts or campaigns,NaN,Marketing or advertising materials,"Participation in industry events, panels, or c...","Collaboration with media outlets (e.g., interv...",...,NaN,NaN,NaN,Data accuracy issues,Employee fears of job loss and/or replacement,NaN,"Negative economic outcomes (e.g. AI bubble, ma...",NaN,NaN,NaN
3,Response 2,Decreased,Stayed the same,NaN,Company blog posts or thought leadership articles,NaN,NaN,NaN,"Participation in industry events, panels, or c...","Collaboration with media outlets (e.g., interv...",...,Deepfakes of CEO/corporate executives,NaN,Data security and/or privacy issues,Data accuracy issues,NaN,NaN,NaN,NaN,NaN,NaN
4,Response 3,Decreased,Stayed the same,NaN,NaN,NaN,NaN,NaN,"Participation in industry events, panels, or c...",NaN,...,NaN,Spread of misinformation,Data security and/or privacy issues,Data accuracy issues,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Checking rows x columns
labels_df.shape

(47, 52)

In [ ]:
#Checking column names
labels_df.columns

Index(['ExternalReference', 'Q2', 'Q3', 'Q4_1', 'Q4_2', 'Q4_3', 'Q4_4', 'Q4_5',
       'Q4_6', 'Q4_7', 'Q4_8', 'Q4_9', 'Q4_8_TEXT', 'Q5_1', 'Q5_2', 'Q5_3',
       'Q5_4', 'Q5_5', 'Q5_6', 'Q5_7', 'Q5_6_TEXT', 'Q6', 'Q7_1', 'Q7_2',
       'Q7_3', 'Q7_4', 'Q7_5', 'Q7_6', 'Q7_7', 'Q7_8', 'Q8_1', 'Q8_2', 'Q8_3',
       'Q8_4', 'Q8_5', 'Q8_6', 'Q8_7', 'Q8_8', 'Q8_9', 'Q8_10', 'Q8_9_TEXT',
       'Q9', 'Q10_1', 'Q10_2', 'Q10_3', 'Q10_4', 'Q10_5', 'Q10_6', 'Q10_7',
       'Q10_8', 'Q10_9', 'Q10_8_TEXT'],
      dtype='object')

In [ ]:
#Checking missing values
labels_df.isnull().sum()

ExternalReference     0
Q2                    0
Q3                    0
Q4_1                 27
Q4_2                 21
Q4_3                 33
Q4_4                 19
Q4_5                 36
Q4_6                 16
Q4_7                 28
Q4_8                 43
Q4_9                 37
Q4_8_TEXT            43
Q5_1                 10
Q5_2                 18
Q5_3                 35
Q5_4                  9
Q5_5                  9
Q5_6                 45
Q5_7                 45
Q5_6_TEXT            45
Q6                   35
Q7_1                  2
Q7_2                 38
Q7_3                 10
Q7_4                 20
Q7_5                 36
Q7_6                 33
Q7_7                 30
Q7_8                 23
Q8_1                 10
Q8_2                 28
Q8_3                  6
Q8_4                 10
Q8_5                 27
Q8_6                 31
Q8_7                 32
Q8_8                 35
Q8_9                 41
Q8_10                45
Q8_9_TEXT            41
Q9                    0
Q10_1                33
Q10_2                21
Q10_3                11
Q10_4                20
Q10_5                25
Q10_6                44
Q10_7                40
Q10_8                43
Q10_9                45
Q10_8_TEXT           43
dtype: int64

# Reorganizing Data Structure

In [ ]:
#Reloading dataset so row slicing always happens on original data
labels_df = pd.read_excel("FILE A.xlsx")

#Removing first two rows: Qualtrics metadata (question text & import IDs)
#Resetting index so pandas can pick up responses 1-4
labels_df = labels_df.iloc[2:].reset_index(drop=True)

#Checking dataset
labels_df.head()

,ExternalReference,Q2,Q3,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,...,Q10_1,Q10_2,Q10_3,Q10_4,Q10_5,Q10_6,Q10_7,Q10_8,Q10_9,Q10_8_TEXT
0,Response 1,Decreased,Stayed the same,Public statements or press releases,Company blog posts or thought leadership articles,Social media posts or campaigns,NaN,Marketing or advertising materials,"Participation in industry events, panels, or c...","Collaboration with media outlets (e.g., interv...",...,NaN,NaN,NaN,Data accuracy issues,Employee fears of job loss and/or replacement,NaN,"Negative economic outcomes (e.g. AI bubble, ma...",NaN,NaN,NaN
1,Response 2,Decreased,Stayed the same,NaN,Company blog posts or thought leadership articles,NaN,NaN,NaN,"Participation in industry events, panels, or c...","Collaboration with media outlets (e.g., interv...",...,Deepfakes of CEO/corporate executives,NaN,Data security and/or privacy issues,Data accuracy issues,NaN,NaN,NaN,NaN,NaN,NaN
2,Response 3,Decreased,Stayed the same,NaN,NaN,NaN,NaN,NaN,"Participation in industry events, panels, or c...",NaN,...,NaN,Spread of misinformation,Data security and/or privacy issues,Data accuracy issues,NaN,NaN,NaN,NaN,NaN,NaN
3,Response 4,Increased,Stayed the same,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Data accuracy issues,Employee fears of job loss and/or replacement,NaN,NaN,NaN,NaN,NaN
4,Response 5,Increased,Increased ‚Äì we are responding to employees more,Public statements or press releases,Company blog posts or thought leadership articles,Social media posts or campaigns,Earnings calls or investor presentations,Marketing or advertising materials,"Participation in industry events, panels, or c...","Collaboration with media outlets (e.g., interv...",...,NaN,NaN,Data security and/or privacy issues,NaN,Employee fears of job loss and/or replacement,NaN,"Negative economic outcomes (e.g. AI bubble, ma...",NaN,NaN,NaN

In [ ]:
#Checking for duplicates (I noticed in File A there were no Response ID duplicates,
#so I am checking if two rows have identical answers across all questions even with different Response #
#(Example: one response got recorded twice for some reason)
labels_no_id = labels_df.drop(columns=['ExternalReference'])
duplicate_responses = labels_no_id.duplicated().sum()

print("# of duplicates:", duplicate_responses)
#Looks like we're good

# of duplicates: 0

In [ ]:
#Checking invalid responses "Prefer not to answer" (I didn't see any, but just in case I missed it)
labels_df.apply(lambda col: col.astype(str).str.contains("Prefer", case=False).sum())

#Looks like there are none

ExternalReference    0
Q2                   0
Q3                   0
Q4_1                 0
Q4_2                 0
Q4_3                 0
Q4_4                 0
Q4_5                 0
Q4_6                 0
Q4_7                 0
Q4_8                 0
Q4_9                 0
Q4_8_TEXT            0
Q5_1                 0
Q5_2                 0
Q5_3                 0
Q5_4                 0
Q5_5                 0
Q5_6                 0
Q5_7                 0
Q5_6_TEXT            0
Q6                   0
Q7_1                 0
Q7_2                 0
Q7_3                 0
Q7_4                 0
Q7_5                 0
Q7_6                 0
Q7_7                 0
Q7_8                 0
Q8_1                 0
Q8_2                 0
Q8_3                 0
Q8_4                 0
Q8_5                 0
Q8_6                 0
Q8_7                 0
Q8_8                 0
Q8_9                 0
Q8_10                0
Q8_9_TEXT            0
Q9                   0
Q10_1                0
Q10_2                0
Q10_3                0
Q10_4                0
Q10_5                0
Q10_6                0
Q10_7                0
Q10_8                0
Q10_9                0
Q10_8_TEXT           0
dtype: int64

In [ ]:
#Standardizing all blank spaces, just to make sure all white spaces/no responses are
#counted as missing values
labels_df = labels_df.replace(r'^\s*$', np.nan, regex=True)

/tmp/ipykernel_823/2503767821.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  labels_df = labels_df.replace(r'^\s*$', np.nan, regex=True)

In [ ]:
#Now separating question columns for percentage computation
question_columns = labels_df.columns.drop("ExternalReference")

# Grouping questions into single select, multi select, and text fields.

In [ ]:
import re
from collections import defaultdict

#Grouping multi-select columns
multi_select_groups = defaultdict(list)
single_select_columns = []

#Identifying columns that follow the Q(x)_(y) format
for col in question_columns:
    if re.match(r"^Q\d+_\d+$", col):
        base_question = col.rsplit("_", 1)[0]
        multi_select_groups[base_question].append(col)
    #Excluding TEXT columns
    elif not col.endswith("_TEXT"):
        single_select_columns.append(col)

#Sorting multi-select columns numerically within each question group
for question in multi_select_groups:
    multi_select_groups[question] = sorted(
        multi_select_groups[question],
        key=lambda x: int(x.split("_")[1])
    )

#Creating summary results
results = []

In [ ]:
#Creating counts for single-select questions
for col in single_select_columns:
    valid_responses = labels_df[col].dropna()

    #Defining count
    counts = valid_responses.value_counts()
    total_valid = counts.sum()

    for response, count in counts.items():
        #Calculating percent
        percent = (count / total_valid) * 100 if total_valid > 0 else 0

        results.append({
            "question": col,
            "response_option": response,
            "count_n": count,
            "percent": round(percent, 2),
            "denominator_n": total_valid,
            "question_type": "single_select"
        })

In [ ]:
#Creating counts for multi-select questions
#For the denominator, I used the number of respondents who selected at least one option
for question, cols in multi_select_groups.items():
    subset = labels_df[cols]

    #Number of respondents who selected at least one option
    respondents_answered = subset.notna().any(axis=1).sum()

    for col in cols:
        count = subset[col].notna().sum()

        #I used the actual answer text from the labels file instead of Q10_1, Q10_2, etc.
        non_missing_values = subset[col].dropna().unique()
        if len(non_missing_values) == 1:
            option_label = non_missing_values[0]
        elif len(non_missing_values) > 1:
            option_label = " / ".join(sorted(map(str, non_missing_values)))
        else:
            option_label = col

        #Calculating Percent
        percent = (count / respondents_answered) * 100 if respondents_answered > 0 else 0

        results.append({
            "question": question,
            "response_option": option_label,
            "count_n": count,
            "percent": round(percent, 1),
            "denominator_n": respondents_answered,
            "question_type": "multi_select"
        })

In [ ]:
#Results table
results_df = pd.DataFrame(results)

#Cleaning up table:

#Sorting questions numerically so Q10 appears after Q9 instead of before Q2
results_df["question_number"] = results_df["question"].str.extract(r"Q(\d+)").astype(int)
#Fixing "Äì" error that shows up in some answers, small nitpick
results_df["response_option"] = results_df["response_option"].str.replace("‚Äì", "–")
#Rounding percentage
results_df["percent"] = results_df["percent"].round(1)

#Creating final table, sorting how I want for each column
results_df = results_df.sort_values(
    by=["question_number", "question_type", "count_n", "response_option"],
    ascending=[True, True, False, True]
).drop(columns="question_number").reset_index(drop=True)

print(results_df.to_string(index=False))

question                                                                               response_option  count_n  percent  denominator_n question_type
      Q2                                                                               Stayed the same       23     51.1             45 single_select
      Q2                                                                                     Decreased       18     40.0             45 single_select
      Q2                                                                                     Increased        4      8.9             45 single_select
      Q3                                                                               Stayed the same       34     75.6             45 single_select
      Q3                                               Decreased – we are responding to employees less        7     15.6             45 single_select
      Q3                                               Increased – we are responding to employees more        4      8.9             45 single_select
      Q4                                      Participation in industry events, panels, or conferences       29     64.4             45  multi_select
      Q4                                                      Earnings calls or investor presentations       26     57.8             45  multi_select
      Q4                                             Company blog posts or thought leadership articles       24     53.3             45  multi_select
      Q4                                                           Public statements or press releases       18     40.0             45  multi_select
      Q4                                   Collaboration with media outlets (e.g., interviews, op-eds)       17     37.8             45  multi_select
      Q4                                                               Social media posts or campaigns       12     26.7             45  multi_select
      Q4                                                            Marketing or advertising materials        9     20.0             45  multi_select
      Q4                                               Not currently communicating externally about AI        8     17.8             45  multi_select
      Q4                                                                        Other (please specify)        2      4.4             45  multi_select
      Q5                                                 Communicating possible use cases for AI-tools       36     80.0             45  multi_select
      Q5                                             Encouraging general experimentation with AI-tools       36     80.0             45  multi_select
      Q5                                        Conducting standardized training for specific AI-tools       35     77.8             45  multi_select
      Q5                                                   Offering subscription for specific AI-tools       27     60.0             45  multi_select
      Q5                                          Requiring use of specific AI-tools for certain tasks       10     22.2             45  multi_select
      Q5                                                                                          Q5_6        0      0.0             45  multi_select
      Q5                                                                                          Q5_7        0      0.0             45  multi_select
      Q6                                                                                       Copilot        4     40.0             10 single_select
      Q6                                                                                briefing notes        1     10.0             10 single_select
      Q6                                                                            case by case basis        1     10.0             10 single_select
      Q6                                                                              customer service        1     10.0             10 single_select
      Q6                                                                               data anslytics         1     10.0             10 single_select
      Q6                                                                                    efficiency        1     10.0             10 single_select
      Q6                                                                      research and development        1     10.0             10 single_select
      Q7                               Generative AI for text (e.g., ChatGPT, Claude, Gemini, Copilot)       43     95.6             45  multi_select
      Q7       AI for productivity and collaboration (e.g., Microsoft Copilot, Google Duet, Notion AI)       35     77.8             45  multi_select
      Q7 AI for data analysis and business intelligence (e.g., Tableau AI, Power BI with AI, SAS Viya)       25     55.6             45  multi_select
      Q7                                                                 Proprietary in-house AI tools       22     48.9             45  multi_select
      Q7  AI for coding and software development (e.g., GitHub Copilot, Amazon CodeWhisperer, Tabnine)       15     33.3             45  multi_select
      Q7                                AI for HR and recruiting (e.g., HireVue, Eightfold, Pymetrics)       12     26.7             45  multi_select
      Q7           AI for marketing and customer engagement (e.g., Jasper, Persado, Drift, HubSpot AI)        9     20.0             45  multi_select
      Q7                 Generative AI for images/video (e.g., Midjourney, DALL¬∑E, Runway, Synthesia)        7     15.6             45  multi_select
      Q8                                                        Data analytics / business intelligence       39     86.7             45  multi_select
      Q8                                                                    Communications / marketing       35     77.8             45  multi_select
      Q8                                                        IT / engineering / product development       35     77.8             45  multi_select
      Q8                                                                  Human resources / recruiting       18     40.0             45  multi_select
      Q8                                                                      Sales / customer service       17     37.8             45  multi_select
      Q8                                                                            Legal / compliance       14     31.1             45  multi_select
      Q8                                                                          Finance / operations       13     28.9             45  multi_select
      Q8                                                                Executive leadership / C-suite       10     22.2             45  multi_select
      Q8                                                                        Other (please specify)        4      8.9             45  multi_select
      Q8                                                                                         Q8_10        0      0.0             45  multi_select
      Q9                         We are currently somewhere in the middle when it comes to AI adoption       31     68.9             45 single_select
      Q9                                                         We are behind the pack in AI adoption        6     13.3             45 single_select
      Q9                                              We are currently leading the race in AI adoption        5     11.1             45 single_select
      Q9                                                                           Don‚Äôt know/Unsure        3      6.7             45 single_select
     Q10                                                           Data security and/or privacy issues       34     75.6             45  multi_select
     Q10                                                                          Data accuracy issues       25     55.6             45  multi_select
     Q10                                                                      Spread of misinformation       24     53.3             45  multi_select
     Q10                                                 Employee fears of job loss and/or replacement       20     44.4             45  multi_select
     Q10                                                         Deepfakes of CEO/corporate executives       12     26.7             45  multi_select
     Q10      Negative economic outcomes (e.g. AI bubble, market downturn due to poor earnings, etc.)         5     11.1             45  multi_select
     Q10                                                                        Other (please specify)        2      4.4             45  multi_select
     Q10                                                            Activist pressure against AI usage        1      2.2             45  multi_select
     Q10                                                                                         Q10_9        0      0.0             45  multi_select

In [ ]:
#Exporting this cleaned dataset into excel for future data analysis or creating visualizations
results_df.to_excel("survey_summary_results.xlsx", index=False)

Part 1: Data Analysis Notes / Explaining Work


*   Valid responses were defined as not blank, NA, or missing
*   For single select questions (Q2, Q3, Q6, Q9), I calculated count by dividing the count of response options/total valid responses to the question *100.


*   For multi select questions (Q4, Q5, Q7, Q8, Q10) I considered the question answered if at least one option was selected within the group. The denominator for calculating percentage was the number of respondents who selected at least one option. Each question was answered, so the denominator remained at 45 (except Q6 which was optional).
*   I did not include open-text fields that correspond with the "Other (please specify)" choice

*   Exported cleaned dataset into Excel to be used for the next part of the assessment